"""Async database foundation: engine, session factory, declarative base, RLS session.

The app connects as the non-superuser role so Postgres row-level security
applies (§4.2). Each request gets one session inside one transaction; when the
request has a resolved tenant, the transaction sets ``app.tenant_id`` with
``set_config(..., is_local => true)`` so every RLS-protected table is scoped
to that tenant for the duration of the transaction — even a buggy query cannot
cross tenants.
"""

import uuid
from collections.abc import AsyncIterator, Awaitable, Callable
from datetime import datetime
from typing import Annotated, Any, ClassVar

import structlog
from fastapi import Depends, Request
from sqlalchemy import TIMESTAMP, MetaData, func, text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.ext.asyncio import (
    AsyncEngine,
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from uuid_utils.compat import uuid7

from app.core.config import Settings

logger = structlog.get_logger(__name__)

# Deterministic constraint names — required for reviewable autogenerated migrations.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)
    type_annotation_map: ClassVar[dict[Any, Any]] = {
        datetime: TIMESTAMP(timezone=True),
        dict[str, Any]: JSONB,
    }
    # Async sessions cannot lazy-refresh expired attributes; fetch
    # server-generated values (updated_at's onupdate) via RETURNING at flush.
    __mapper_args__ = {"eager_defaults": True}  # noqa: RUF012


class UUIDPrimaryKeyMixin:
    """UUIDv7 primary key: time-ordered, so it doubles as a stable keyset column."""

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid7)


class TimestampMixin:
    created_at: Mapped[datetime] = mapped_column(server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(server_default=func.now(), onupdate=func.now())


def create_engine(settings: Settings) -> AsyncEngine:
    return create_async_engine(settings.database_url, pool_pre_ping=True)


def create_session_factory(engine: AsyncEngine) -> async_sessionmaker[AsyncSession]:
    return async_sessionmaker(engine, expire_on_commit=False)


async def set_tenant_guc(session: AsyncSession, tenant_id: uuid.UUID) -> None:
    """Scope the current transaction to one tenant (``SET LOCAL app.tenant_id``)."""
    await session.execute(
        text("SELECT set_config('app.tenant_id', :tenant_id, true)"),
        {"tenant_id": str(tenant_id)},
    )


def on_commit(session: AsyncSession, callback: Callable[[], Awaitable[None]]) -> None:
    """Register an async callback to run only after the request transaction
    commits (e.g. cache invalidation — running it earlier would let a
    concurrent reader re-cache the not-yet-committed state).

    Callbacks are **isolated from each other**: each runs in its own
    ``try``/``except``, so one raising is logged and the rest still run. They
    are also **best-effort** — they fire after the commit, so a failure cannot
    roll anything back and is not reported to the caller. A side effect that
    must not be lost belongs in the transactional outbox (``core.events``),
    which commits with the row and is retried by the relay.
    """
    session.info.setdefault("post_commit_callbacks", []).append(callback)


async def get_session(request: Request) -> AsyncIterator[AsyncSession]:
    """Request-scoped session: one transaction, tenant-scoped when resolved.

    Commits on success, rolls back when the route raises. Services flush but
    never commit — the request boundary owns the transaction.
    """
    session_factory: async_sessionmaker[AsyncSession] = request.app.state.session_factory
    async with session_factory() as session:
        async with session.begin():
            tenant = getattr(request.state, "tenant", None)
            if tenant is not None:
                await set_tenant_guc(session, tenant.id)
            yield session
        # Reached only on successful commit; skipped when the route raised.
        callbacks: list[Callable[[], Awaitable[None]]]
        callbacks = session.info.get("post_commit_callbacks", [])
        for callback in callbacks:
            try:
                await callback()
            except Exception:
                # Callbacks are independent side effects of an *already
                # committed* transaction (cache invalidation, task enqueues).
                # One failing — a Redis blip during an invalidation, a broker
                # hiccup — must not skip the rest: the row is durable either
                # way, and silently dropping the remaining callbacks would
                # leave a partially-invalidated cache or an unqueued job with
                # no signal. Logged and stepped over instead; anything that
                # cannot tolerate being lost belongs in the transactional
                # outbox (``core.events``), not here.
                logger.exception("post_commit_callback_failed")


SessionDep = Annotated[AsyncSession, Depends(get_session)]
